fix: Barbican use same uwsgi config as other services.
vexxhost/atmosphere pull request #1119
Opened 2024-04-16 12:16 UTC by ricolin

This renew Barbican uwsgi config and make sure it uses same uwsgi config as other services.

2024-04-16 21:14 UTC, mnaser commented
@ricolin 

Two issues with this change

1. I have no idea how the CI didn't catch that there wasn't a patch included.. it should have failed because there is a missing patch.
2. We either need to push this upstream and add it as a patch into `.charts.yml` or add it as a local patch.

2024-04-16 21:15 UTC, mnaser commented
/cherry-pick stable/zed

2024-04-17 03:09 UTC, ricolin commented
> @ricolin
> 
> Two issues with this change
> 
> 1. I have no idea how the CI didn't catch that there wasn't a patch included.. it should have failed because there is a missing patch.
> 2. We either need to push this upstream and add it as a patch into .charts.yml or add it as a local patch.

No problem, I was targeting of shift it to upstream once we approve it, but let me link from path now

2024-04-17 11:48 UTC, mnaser requested changes

2024-04-17 11:48 UTC, mnaser commented on charts/barbican/charts/helm-toolkit/Chart.yaml
> -version: 0.2.55
Please pin helm-toolkit to 0.2.55 as we've done in the other charts in order to avoid a this big commit change and make it a much smaller change.

2024-04-17 18:06 UTC, mnaser requested changes
@ricolin :

Can you make a follow-up patch similar to these?

https://github.com/vexxhost/atmosphere/blob/main/charts/patches/cinder/0001-tune-uwsgi-config.patch

2024-04-19 00:04 UTC, mnaser commented
@ricolin Since we are actually using backports now and have stable branches, we're trying to avoid bumps on master branch for changes that would be backported (such as this one).

We can have another seperate PR for the bump that we would not backport

2024-04-19 02:55 UTC, mnaser commented
recheck

2024-04-19 04:39 UTC, ricolin commented
> @ricolin Since we are actually using backports now and have stable branches, we're trying to avoid bumps on master branch for changes that would be backported (such as this one).
> 
> We can have another seperate PR for the bump that we would not backport

I just put them to here now https://github.com/vexxhost/atmosphere/pull/1136

2024-04-19 19:42 UTC, mnaser commented
regate

2024-04-21 00:39 UTC, mnaser commented
regate

2024-04-21 03:44 UTC, mnaser commented
regate

2024-04-21 03:45 UTC, mnaser approved these changes

2024-04-21 14:32 UTC, mnaser commented
regate

2024-04-21 16:08 UTC, merged