fix: correct keystone_domains reference from horizon
vexxhost/atmosphere pull request #1182
Opened 2024-05-03 17:34 UTC by ricolin

fix https://github.com/vexxhost/atmosphere/issues/727

2024-05-14 06:13 UTC, ricolin commented
recheck

2024-07-02 13:41 UTC, mnaser requested changes

2024-07-02 13:41 UTC, mnaser commented on roles/horizon/vars/main.yml
> -            idp_mapping: "{{ keystone_domains | default([{'name': 'atmosphere', 'label': 'Atmosphere'}]) | vexxhost.atmosphere.keystone_domains_to_idp_mappings }}" # noqa: yaml[line-length]
@ricolin I think the cleaner way to do this with making less changes (but it's very stinky).

```yaml
idp_mapping: "{{ keystone_domains | default([{'name': (keystone_keycloak_realm | default('atmosphere')), 'label': (keystone_keycloak_realm_name | default('Atmosphere'))}]) | vexxhost.atmosphere.keystone_domains_to_idp_mappings }}" # noqa: yaml[line-length]
```

2024-07-04 14:41 UTC, mnaser commented
/cherry-pick stable/2024.1

2024-07-04 14:41 UTC, mnaser commented
/cherry-pick stable/2023.2

2024-07-04 15:42 UTC, mnaser approved these changes

2024-07-04 17:23 UTC, merged