fix: allow prometheus extend rule
vexxhost/atmosphere pull request #1215
Opened 2024-05-15 15:02 UTC by ricolin

fix: https://github.com/vexxhost/atmosphere/issues/738

2024-06-28 18:42 UTC, mnaser requested changes
I see a few issues with this current approach.

This means that there's no way of actually editing the existing rules, this is just extending/adding to the additional existing rules.  This means that this can simply be replaced with `kube_prometheus_stack_helm_values.additionalPrometheusRulesMap` instead which becomes just a documentation change.

I'd rather we do that than introduce a new variable for this.

2024-06-28 21:06 UTC, mpiscaer commented
Is don't know if i understand this correctly but when you use at the combine filter use 'list_merge=append' it will extend the string and then you can use the feature from jsonnet to overide/extend the existing settings.

2024-07-02 07:40 UTC, ricolin commented
> I see a few issues with this current approach.
> 
> This means that there's no way of actually editing the existing rules, this is just extending/adding to the additional existing rules. This means that this can simply be replaced with `kube_prometheus_stack_helm_values.additionalPrometheusRulesMap` instead which becomes just a documentation change.
> 
> I'd rather we do that than introduce a new variable for this.

If we need override existing, another way we I can try is to write an ansible plugin so we can handle combine on real recursive ( and avoid constraint that brought by existing combine function https://github.com/vexxhost/atmosphere/pull/1215/files#diff-2162201c39f35aed971e9b5b2fc33cb1860cfa756c8cf776683d15fe686b9cfaR291-R296 )

2024-07-05 07:01 UTC, ricolin commented
> @mnaser Is don't know if i understand this correctly but when you use at the combine filter use 'list_merge=append' it will extend the string and then you can use the feature from jsonnet to overide/extend the existing settings.

The issue with directly using list_merge=append for combine, is that will give us two rule group with same name and makes error for charts like 
```
{ 
    "ipmi-exporter": {
        "groups": [
            {
                "name": "rules",
                "rules": [ { "alert": "IpmiCollectorDown", "expr": "ipmi_up == 0", "for": "10m", "labels": {"severity": "P3"}, } ],
            },
            {
                "name": "rules",
                "rules": [ { "alert": "IpmiCollectorDown", "expr": "ipmi_up == 0", "for": "16m", "labels": {"severity": "P2"}, } ],
            },
        ]
    }   
}
```
I just added a plugin to handle that error

2024-09-27 05:34 UTC, ricolin commented
recheck

2025-02-17 16:40 UTC, closed without merging