[ATMOSPHERE-362] generate_workspace: Set mgr/cephadm/warn_on_stray_daemons to false
vexxhost/atmosphere pull request #1241
Opened 2024-05-24 21:19 UTC by gtirloni

When rook-ceph deploys daemon outside of cephadm purview, cephadm will trigger a warning about stray daemons, putting the cluster in HEALTH_WARN state.

https://docs.ceph.com/en/latest/cephadm/operations/#cephadm-stray-daemon

2024-05-26 11:22 UTC, mnaser requested changes
This is awesome.  This fix that Rico implemented was not so clean but I didn't know this existed.

https://github.com/vexxhost/atmosphere/blob/abb177586fda668aea747e54231d5d1630bfb57e/roles/rook_ceph_cluster/tasks/main.yml#L15-L22

I would push to make this an option in `ansible-collection-ceph` and then when Atmosphere calls it, we make it disable this option.  What do you think?

2024-06-04 09:04 UTC, ricolin commented
I think we should also backport this to 2023.1 and zed too

2024-07-05 16:06 UTC, gtirloni commented
@ricolin @mnaser  so the ceph collection accepts `ceph_conf_overrides` already and it's just an option in an ini file. Since it's inherent to the way atmosphere deploys Ceph, I've moved it from generate_workspace (which is optional, AFAIK) to the ceph playbook here so it's always applied. Does that look okay? If you think it's better to have a variable in some role in the ceph collection to disable/enable this, I can do that as well.

2024-07-12 03:57 UTC, ricolin commented
recheck

2024-07-16 19:36 UTC, gtirloni commented
@ricolin any tips about how to extract the state of the pod that's stuck in Pending in this CI build? i can't reproduce locally but my setup might be different.

2024-07-19 20:50 UTC, gtirloni commented
recheck

2024-08-05 13:38 UTC, gtirloni commented
recheck

2024-08-23 02:00 UTC, mnaser approved these changes

2024-08-23 03:53 UTC, merged

2024-08-23 11:50 UTC, mnaser commented
/cherry-pick stable/2024.1

2024-08-23 11:50 UTC, mnaser commented
/cherry-pick stable/2023.2

2024-08-23 11:50 UTC, mnaser commented
/cherry-pick stable/2023.1

2024-08-23 11:50 UTC, mnaser commented
/cherry-pick stable/zed