feat: add nova chart patch for rbd backend init
vexxhost/atmosphere pull request #1270
Opened 2024-05-30 20:43 UTC by fitbeard

https://review.opendev.org/c/openstack/openstack-helm/+/904429

2024-05-30 20:44 UTC, fitbeard commented
clean patch from `tox -e sync-charts` output

2024-06-01 18:18 UTC, mnaser commented
We're pinned at `0.3.27` right now for Nova, since then:

```
  - 0.3.27 Add 2023.2 Ubuntu Jammy overrides
  - 0.3.28 Add ability to define extra command(s) for the nova cell setup job
  - 0.3.29 Add ability to define extra command(s) for the nova service cleaner job
  - 0.3.30 Add the conditional statement for log_config_append
  - 0.3.31 Add getting LISTEN IP for CIDR
  - 0.3.32 Set the startupProbe for nova-compute
  - 0.3.33 Add job to create 'vms' pool
  - 0.3.34 Add public endpoints for the spiceproxy
  - 0.3.35 Use directory mount for vencrypt certificates
  - 0.3.36 Update Ceph images to Jammy and Reef 18.2.1
  - 0.3.37 Use metadata_listen_port instead of metadata_port
  - 0.3.38 Using uWSGI
  - 0.3.39 Enable custom annotations for Openstack pods
  - 0.3.40 Add 2024.1 overrides
  - 0.3.41 Enable custom annotations for Openstack secrets
  - 0.3.42 Update images used by default
```

The current patches are:

- 0.3.32 Set the startupProbe for nova-compute (904250)
- 0.3.33 Add job to create 'vms' pool (904429)
- 0.3.38 Using uWSGI (899809)

Also, I think that @okozachenko1203 was trying to get https://github.com/vexxhost/atmosphere/pull/871/files in which is `0.3.35`.

Would it be possible to jump bump to 0.3.42 and drop all the patches?  The only issue is `0.3.34` adds the new endpoints:

https://github.com/openstack/openstack-helm/commit/3620054deffc253caa80a44a8c18cf82cdd50c69

So it might just need adding:

```
manifests:
  ingress_spiceproxy: false
  service_ingress_spiceproxy: false
```

If you have sometime to take care of this, that would be cool but if you dont have time beyond fixing this vm patch I have no problem to do it.

2024-06-01 18:18 UTC, mnaser requested changes
We're pinned at `0.3.27` right now for Nova, since then:

```
  - 0.3.27 Add 2023.2 Ubuntu Jammy overrides
  - 0.3.28 Add ability to define extra command(s) for the nova cell setup job
  - 0.3.29 Add ability to define extra command(s) for the nova service cleaner job
  - 0.3.30 Add the conditional statement for log_config_append
  - 0.3.31 Add getting LISTEN IP for CIDR
  - 0.3.32 Set the startupProbe for nova-compute
  - 0.3.33 Add job to create 'vms' pool
  - 0.3.34 Add public endpoints for the spiceproxy
  - 0.3.35 Use directory mount for vencrypt certificates
  - 0.3.36 Update Ceph images to Jammy and Reef 18.2.1
  - 0.3.37 Use metadata_listen_port instead of metadata_port
  - 0.3.38 Using uWSGI
  - 0.3.39 Enable custom annotations for Openstack pods
  - 0.3.40 Add 2024.1 overrides
  - 0.3.41 Enable custom annotations for Openstack secrets
  - 0.3.42 Update images used by default
```

The current patches are:

- 0.3.32 Set the startupProbe for nova-compute (904250)
- 0.3.33 Add job to create 'vms' pool (904429)
- 0.3.38 Using uWSGI (899809)

Also, I think that @okozachenko1203 was trying to get https://github.com/vexxhost/atmosphere/pull/871/files in which is `0.3.35`.

Would it be possible to jump bump to 0.3.42 and drop all the patches?  The only issue is `0.3.34` adds the new endpoints:

https://github.com/openstack/openstack-helm/commit/3620054deffc253caa80a44a8c18cf82cdd50c69

So it might just need adding:

```
manifests:
  ingress_spiceproxy: false
  service_ingress_spiceproxy: false
```

If you have sometime to take care of this, that would be cool but if you dont have time beyond fixing this vm patch I have no problem to do it.

2025-02-24 16:11 UTC, mnaser commented
I believe this is already landed now.

2025-02-24 16:11 UTC, closed without merging