fix: zed upgrade to 2023.1
vexxhost/atmosphere pull request #1308
Opened 2024-06-05 03:43 UTC by ricolin

2024-06-05 08:03 UTC, ricolin commented
TODO move docs/* and roles/* to master PR

2024-06-05 12:43 UTC, mnaser commented
https://github.com/vexxhost/atmosphere/pull/1310

2024-06-05 12:51 UTC, mnaser commented
https://github.com/vexxhost/atmosphere/pull/1313

2024-06-05 12:51 UTC, mnaser commented on doc/source/upgrade/index.rst
> +    * node-feature-discovery-worker
For the CRDs, I pushed up https://github.com/vexxhost/atmosphere/pull/1313

2024-06-05 12:52 UTC, mnaser commented on roles/ingress_nginx/vars/main.yml
> +    allowSnippetAnnotations: true
I pushed https://github.com/vexxhost/atmosphere/pull/1310 for this

2024-06-06 02:59 UTC, ricolin commented on doc/source/upgrade/index.rst
> +    * prometheus-pushgateway
added in https://github.com/vexxhost/atmosphere/pull/1319

2024-06-12 08:25 UTC, ricolin commented
recheck

2024-06-17 12:40 UTC, mnaser requested changes
I think for this we are looking ok but we need to refactor the upgrade job into the master branch so when we create a branch, it is easily back portable, so we just create a new job when we branch a new release from the base.

2024-06-17 12:40 UTC, mnaser commented on zuul.d/playbooks/upgrade/run-zed-2023.1.yml
> +        export ATMOSPHERE_NETWORK_BACKEND=openvswitch
Please move this into the `environment` section

2024-06-17 12:40 UTC, mnaser commented on zuul.d/playbooks/upgrade/run-zed-2023.1.yml
> +        export ATMOSPHERE_NETWORK_BACKEND=openvswitch
This needs to be moved to environment too.

2024-06-17 12:40 UTC, mnaser commented on zuul.d/jobs.yaml
> +    parent: atmosphere-molecule-upgrade-aio
Can you make this a base, and then add both scenarios for Open Switch and OVN?

2024-06-17 12:40 UTC, mnaser commented on zuul.d/playbooks/upgrade/run-zed-2023.1.yml
> +        git checkout stable/zed
Can you make this a variable in the upgrade job so we can change the variable and reuse the job?

2024-06-17 12:40 UTC, mnaser commented on zuul.d/playbooks/upgrade/run-zed-2023.1.yml
> +        line: 'rabbitmq_skip_spec_diff: true'
Is this necessary?  In my experience, only when you have a TTY it will block, but in CI or when there is automation, it skips right through.

2024-06-17 12:40 UTC, mnaser commented on zuul.d/playbooks/upgrade/run-zed-2023.1.yml
> +        git checkout stable/2023.1
Let's also template the target branch here.

2024-07-19 00:55 UTC, closed without merging