chore: documentation for upgrade cross stable branches
vexxhost/atmosphere pull request #1324
Opened 2024-06-06 03:13 UTC by ricolin

Related-To: https://github.com/vexxhost/atmosphere/issues/1282
Related-To: https://github.com/vexxhost/atmosphere/pull/1308

2024-06-17 12:42 UTC, mnaser requested changes

2024-06-17 12:42 UTC, mnaser commented on doc/source/upgrade/index.rst
> +    * node-feature-discovery-worker
This is not correct.

2024-06-17 12:42 UTC, mnaser commented on doc/source/upgrade/index.rst
> +    Because RabbitMQ cluster spec changed when across stable/zed to stable/2023.1.
I think this is okay to leave, the warning is there to show that there will be a change that might be a bit disruptive, so I think there's no need to document it.

2024-09-20 12:54 UTC, okozachenko1203 commented
@ricolin could you update this PR?

2025-03-04 18:34 UTC, closed without merging