feat: add neutron_policy_server support
vexxhost/atmosphere pull request #1428
Opened 2024-06-21 13:20 UTC by ricolin

Depends-On https://github.com/vexxhost/neutron-policy-server/pull/1

2024-06-21 13:26 UTC, mnaser requested changes
please run this via uwsgi :)

2024-06-25 12:12 UTC, mnaser requested changes
@ricolin small revision, I think it will make life a lot easier, I think instead of building a new image, we should instead have the existing image install neutron-policy-server in the same image, therefore, it will allow us to co-install and share dependencies and re-use the same image.

I think we will need to finalize that release first though, let me get that through.

2024-06-25 22:52 UTC, mnaser requested changes

2024-06-25 22:52 UTC, mnaser commented on roles/neutron/defaults/main.yml
> +neutron_policy_server_integration_enabled: false
Honestly, I see the usefulness of this for everyone, so let's enable it by default, and add a comment above it and an extra space.

2024-06-26 16:44 UTC, ricolin commented
I think the last uwsgi/image change introduce the failed on CI. Debuging now

2024-07-02 13:48 UTC, mnaser commented
/cherry-pick stable/2024.1

2024-07-02 13:48 UTC, mnaser commented
/cherry-pick stable/2023.1

2024-07-02 13:48 UTC, mnaser commented
/cherry-pick stable/zed

2024-07-02 16:18 UTC, mnaser commented
regate

2024-07-02 18:15 UTC, merged