[stable/zed] chore: use git ref for neutron-vpnaas
vexxhost/atmosphere pull request #1466
Opened 2024-06-27 13:44 UTC by ricolin

relate to https://github.com/vexxhost/atmosphere/pull/1458

2024-06-27 17:41 UTC, mnaser commented
@ricolin I think you'll have to fix the image here

2024-07-08 11:58 UTC, mnaser requested changes
@ricolin can you remove all the `Build` references? I did a fresh rebuild of everything in Zed not long ago.

2024-07-08 13:42 UTC, ricolin commented
> @ricolin can you remove all the `Build` references? I did a fresh rebuild of everything in Zed not long ago.

got it, let me rework now

2024-07-09 12:28 UTC, mnaser approved these changes

2024-07-09 14:15 UTC, merged