doc: Add versions to README.rst
vexxhost/atmosphere pull request #1682
Opened 2024-07-24 19:07 UTC by gtirloni

2024-07-24 21:37 UTC, mnaser requested changes

2024-07-24 21:37 UTC, mnaser commented on .github/workflows/image.yml
> +      - doc/**
We're moving away from GitHub actions so let's drop this.

2024-07-24 21:37 UTC, mnaser commented on zuul.d/container-images/base.yaml
> +      - \.github/
Let's drop this.

2024-07-24 21:37 UTC, mnaser commented on zuul.d/container-images/base.yaml
> +      - \.github/
..and this..

2024-07-24 21:37 UTC, mnaser commented on zuul.d/container-images/base.yaml
> +      - \.github/
and this :)

2024-07-24 21:37 UTC, mnaser commented on zuul.d/jobs.yaml
> +      - \.github/
this too

2024-07-24 21:37 UTC, mnaser commented on zuul.d/jobs.yaml
> +      - \.github/
this to

2024-07-29 12:55 UTC, gtirloni commented
@mnaser ready for review

2024-10-02 00:17 UTC, closed without merging