feat: build images for ovn exporter and ovs exporter
vexxhost/atmosphere pull request #1717
Opened 2024-07-30 14:19 UTC by okozachenko1203

2024-07-30 15:39 UTC, mnaser requested changes
Can you please do multi-stage image builds of the source code, so use ADD ... with the git repo, and then build the Golang binary in one image, and then copy it to the other?

That will make it easier to pin to specific commits, and also add patches if needed.

2024-09-12 02:35 UTC, mnaser requested changes
I think we should run the ovs exporter only on the ovs pods. The ovn exporter can come later to get ovn specific data.

2025-01-07 12:17 UTC, okozachenko1203 commented
ovn passed.
ovs failed because of net conn issue
![image](https://github.com/user-attachments/assets/78ace767-6ef7-49e3-9ca6-86741235408d)

2025-01-07 12:18 UTC, okozachenko1203 commented
recheck

2025-01-15 14:29 UTC, okozachenko1203 commented
https://review.vexxhost.dev/c/atmosphere/+/203

2025-04-14 03:15 UTC, closed without merging