[ATMOSPHERE-589] Add support for nfs_shares_config
vexxhost/atmosphere pull request #2121
Opened 2024-11-13 02:26 UTC by larainema

2024-11-13 14:50 UTC, mnaser requested changes
One last thing missing, we actually need to _replace_ the value of `nfs_shares_config` in the final generated config file to become `/etc/cinder/nfs/{{ $key }}` so that it points to that mount, cause right now it's actually just going to the data still.

2024-11-13 15:58 UTC, larainema commented on charts/cinder/templates/configmap-etc.yaml
> +  nfs_shares_{{ $key }}: |
I think configmap data key should consistent with mount subPath, right?

2024-11-14 03:20 UTC, larainema commented on charts/cinder/templates/deployment-volume.yaml
> +              mountPath: /etc/cinder/nfs/nfs_shares_{{ $key }}
done

2024-11-14 03:20 UTC, larainema commented on charts/cinder/templates/configmap-etc.yaml
> +  nfs_shares_{{ $key }}: |
done

2024-11-18 16:34 UTC, okozachenko1203 submitted a review, later dismissed

2024-11-18 16:34 UTC, okozachenko1203 commented on charts/patches/cinder/0002-add-nfs-support.patch
> ++++ b/charts/cinder/templates/configmap-etc.yaml
```suggestion
diff --git a/cinder/templates/configmap-etc.yaml b/cinder/templates/configmap-etc.yaml
index 1a20ea84..97bfe0f7 100644
--- a/cinder/templates/configmap-etc.yaml
+++ b/cinder/templates/configmap-etc.yaml
```

2024-11-21 02:58 UTC, mnaser commented
recheck

2024-11-22 02:30 UTC, larainema commented
/cherry-pick stable/2024.1

2024-11-22 02:30 UTC, larainema commented
/cherry-pick stable/2023.2

2024-11-22 02:31 UTC, larainema commented
/cherry-pick stable/2023.1

2024-11-22 02:31 UTC, larainema commented
/cherry-pick stable/zed

2024-11-24 00:47 UTC, mnaser approved these changes

2024-11-24 05:27 UTC, merged