Add manila-service-security-group to limit manila ports
vexxhost/atmosphere pull request #412
Opened 2023-05-12 13:59 UTC by ricolin

2023-05-15 08:49 UTC, ricolin commented
@mnaser validated

2023-05-15 13:29 UTC, mnaser approved these changes

2023-05-15 13:31 UTC, mnaser requested changes
@ricolin -- i see a few problems here:

1. We modified the `charts` which are not meant to manually modified, if there are any changes, they should be done via `hack/sync-charts`
2. I prefer that we use the OpenStack Ansible modules instead, they seem to be much better at this, I would use this as an example: https://github.com/vexxhost/atmosphere/blob/main/roles/octavia/tasks/generate_resources.yml#L30-L48

The only thing is you'll have to make sure that you point to the correct project when using the Ansible modules.

2023-05-16 07:36 UTC, ricolin commented
will send another patch asap

2023-05-17 17:08 UTC, mnaser approved these changes

2023-05-17 17:08 UTC, merged