Bump neutron to 0.3.15
vexxhost/atmosphere pull request #489
Opened 2023-07-17 06:23 UTC by ricolin

This sync asap2 patch to community work

2023-07-17 13:38 UTC, ricolin commented
fix https://github.com/vexxhost/atmosphere/pull/489

2023-07-20 04:59 UTC, mnaser requested changes

2023-07-20 04:59 UTC, mnaser commented on roles/neutron/vars/main.yml
> +      enabled: true
I think it's totally ok to keep this at `false` since most folk will not be using hardware offload, so you can just remove this section.

2023-07-20 08:38 UTC, mnaser approved these changes

2023-07-20 12:08 UTC, merged