chore: Upgrade pxc-operator version
vexxhost/atmosphere pull request #729
Opened 2023-11-24 09:28 UTC by okozachenko1203

2023-12-05 13:44 UTC, mnaser requested changes
I asked when you ran this did it do two rollouts (so when operator went up.. did the cluster gets rolled out again?)

2023-12-05 13:44 UTC, mnaser commented on roles/percona_xtradb_cluster_operator/tasks/main.yml
> +#             component: version-service
please remove this since it's all commented

2023-12-06 13:27 UTC, okozachenko1203 commented
> I asked when you ran this did it do two rollouts (so when operator went up.. did the cluster gets rolled out again?)

no, the cluster not rolled out.

2023-12-06 15:35 UTC, mnaser approved these changes

2023-12-06 15:35 UTC, merged