feat: adopt cephadm
vexxhost/atmosphere pull request #752
Opened 2023-12-14 07:39 UTC by ricolin

fix https://github.com/vexxhost/atmosphere/issues/711

2023-12-14 15:33 UTC, mnaser commented on galaxy.yml
> +version: 1.11.0 # x-release-please-version
no need to do this, release-please will take care of this

2024-01-08 09:16 UTC, ricolin commented
waitting https://github.com/vexxhost/ansible-collection-ceph/actions/runs/7425054349

2024-01-10 16:41 UTC, ricolin commented
missed a spot around here https://github.com/vexxhost/ansible-collection-ceph/blob/main/plugins/module_utils/ca_common.py#L80

2024-01-11 08:31 UTC, ricolin commented
> missed a spot around here https://github.com/vexxhost/ansible-collection-ceph/blob/main/plugins/module_utils/ca_common.py#L80
fix pr is out: https://github.com/vexxhost/ansible-collection-ceph/pull/24

2024-01-15 15:26 UTC, ricolin commented
Idempotence is targeting in https://github.com/vexxhost/ansible-collection-containers/pull/15

2024-02-05 16:06 UTC, ricolin commented
just realized I missed rgw that build from rook-ceph currently

2024-02-23 19:00 UTC, mnaser requested changes

2024-02-26 17:08 UTC, ricolin commented on roles/cluster_issuer/tasks/type/self-signed/main.yml
> +  changed_when: false
I think this is introduced by https://github.com/vexxhost/atmosphere/pull/752/files#diff-1ade2795a7b410581d689fb0faa358b769c2d189b2d549e8f530b706f09b2fb7R20
and the only things changed are the update time  in line 173 of attached log file
and resourceVersion in line 178 of attached log file
same thing gose to vexxhost.atmosphere.octavia : Create CAs & Issuers too.

Do you think this is something we should dive into?
[diff.log](https://github.com/vexxhost/atmosphere/files/14407961/diff.log)

2024-02-26 23:46 UTC, mnaser commented
@ricolin can you merge or rebase ?

2024-02-27 16:10 UTC, merged