fix: fix the condition for stafflen
vexxhost/atmosphere pull request #956
Opened 2024-02-13 14:45 UTC by okozachenko1203

2024-02-15 04:02 UTC, ricolin commented
@okozachenko1203  we need to add staffeln to `_openstack_helm_endpoints_ignore` with condition `if not atmosphere_staffeln_enabled`

2024-02-26 06:15 UTC, ricolin approved these changes

2024-02-28 16:18 UTC, mnaser requested changes

2024-04-21 18:24 UTC, mnaser commented
@ricolin can you please look into the merge conflicts please?

2024-12-19 07:32 UTC, ricolin approved these changes

2025-03-04 18:34 UTC, closed without merging